### ISSUE TITLE
Ambiguous use of 'init(string InterpolationSegment:)'

### ISSUE THREAD

**Issue by whittenator** [T-Pham/NoOptionalInterpolation#1]
Im getting this error for some odd reason now. Any ideas what it could be thanks?
![screen shot 2017-05-08 at 12 11 19 am](https://cloud.githubusercontent.com/assets/17066507/25978377/aa85844c-368f-11e7-93b1-10d7b4aeb92a.png)

I have tried deleting my pod files, reinstalling Cocoapods, cleaning the pod cache, and cleaning the build folders, but nothing has done the trick.

**Comment by Cymric** [comment]
I changed it to String(describing: self) and it compile without error at least. Seriously annoyed that swift syntax are still randomly getting changed so far after it had been released.

**Comment by T-Pham** [comment]
The original purpose of this library is to get rid of "Optional" text in string interpolation. But with [this PR](https://github.com/apple/swift/pull/5110) to the Swift language, there is a warning now for the case, making this library somehow obsolete.

**Comment by T-Pham** [comment]
Version 4.0.0 fixes this.
